// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BiddingController from "./bidding_controller"
application.register("bidding", BiddingController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CarouselThumbController from "./carousel_thumb_controller"
application.register("carousel-thumb", CarouselThumbController)

import CategoryAccessController from "./category_access_controller"
application.register("category-access", CategoryAccessController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PortifolioCategoryController from "./portifolio_category_controller"
application.register("portifolio-category", PortifolioCategoryController)

import ScrollActiveController from "./scroll_active_controller"
application.register("scroll-active", ScrollActiveController)

import ServiceCategoryController from "./service_category_controller"
application.register("service-category", ServiceCategoryController)

import SlideBannerController from "./slide_banner_controller"
application.register("slide-banner", SlideBannerController)

import SlideBlogController from "./slide_blog_controller"
application.register("slide-blog", SlideBlogController)

import SlideClientController from "./slide_client_controller"
application.register("slide-client", SlideClientController)

import SlideNewsController from "./slide_news_controller"
application.register("slide-news", SlideNewsController)

import SlideTestimonyController from "./slide_testimony_controller"
application.register("slide-testimony", SlideTestimonyController)

import VideoController from "./video_controller"
application.register("video", VideoController)
