default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>_development

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
